ETB310_TennantWebsite/Models/ErrorLogItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ETB310_TennantWebsite.Models
{
    public class ErrorLogItem
    {
        public ErrorLogItem(string label, string description)
        {
            TimeStamp = DateTime.Now;
            Label = label;
            Description = description;
        }
        private ErrorLogItem()
        {
        }
        public string Label { get; }
        public DateTime TimeStamp { get; }
        public string Description { get; }
    }
}

ETB310_TennantWebsite/Models/RegistrationConfirmationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ETB310_TennantWebsite.Models
{
    public class RegistrationConfirmationViewModel
    {
        public string CaseNr { get; set; }
        public string FlatNr { get; set; }
        public string Name { get; set; }
        public string ContactEmail { get; set; }
       public string Message { get; set; }
    }
}

ETB310_TennantWebsite/Models/ServiceCasePostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ETB310_TennantWebsite.Models
{
    public class ServiceCasePostViewModel
    {
        public DateTime Date { get; set; } // sätts automatiskt av webbservicen vid sparning 

        public string Message { get; set; } // obligatoriskt 
    }
}

ETB310_TennantWebsite/Models/ServiceCaseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ETB310_TennantWebsite.Models
{
    public class ServiceCaseViewModel
    {
        [Required(ErrorMessage = "Du måste ange ett lägenhetsnumer.")]
        [StringLength(4,ErrorMessage ="Lägenhetsnumret måste var fyra siffror.", MinimumLength =4)]
        [RegularExpression(@"^\d{4}",ErrorMessage ="lägenhetsnumret måste var fyra siffror")]
        public string FlatNr { get; set; } // required 

        [Required(ErrorMessage = "Du måste ange ett namn.")]
        [StringLength(30,ErrorMessage ="Namn måste vara minst 2 tecken och inte längre än 30 tecken", MinimumLength =2)]
        public string Name { get; set; } // required 
        
        [Required(ErrorMessage = "Du måste skriva en emailadres.")]
        [StringLength(40, ErrorMessage = "Epostadressen måste vara minst 6 tecken och inte längre än 40 tecken.", MinimumLength = 6)]
        [RegularExpression(@"[\w\.-_]+@([\w\.-_]+\.)+[a-z]+", ErrorMessage ="Detta är inte en giltig e-postadress")]
        public string ContactEmail { get; set; } // required 

        [Required(ErrorMessage = "Du måste beskriva ditt ärende.")]
        [StringLength(2000, ErrorMessage = "Beskrivningen får inte vara längre än 2000 tecken.")]
        public string NewPostMessage { get; set; } // required 

        public List<ServiceCasePostViewModel> Posts { get; set; }
        public int TryCount { get; set; }
    }
}

ETB310_TennantWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ETB310_TennantWebsite.Models;

namespace ETB310_TennantWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ETB310_TennantWebsite/Controllers/ServiceCaseController.cs
using ETB310_TennantWebsite.MailKit;
using ETB310_TennantWebsite.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace ETB310_TennantWebsite.Controllers
{
    public class ServiceCaseController : Controller
    {
        public ActionResult Index()
        {
            var vm = new ServiceCaseViewModel();
            return View("RegisterServiceCase", vm);
        }

        [HttpPost]
        public ActionResult EditServiceCase(ServiceCaseViewModel vm)
        {
            //ModelState.AddModelError("edit","");
            return View("RegisterServiceCase",vm);
        }

        [HttpPost]
        public ActionResult RegisterServiceCase(ServiceCaseViewModel vm)
        {
            // Kolla att alla inmatade fält är ok och returnera formuläret om nåt är fel
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            // Mappa data från viewmodel till webbservicens klasser 
            var post = new ServiceReference1.ServiceCasePost()
            {
                Message = vm.NewPostMessage,
                Name = vm.Name,
                ContactEmail = vm.ContactEmail
            };
            //  skapa ett ServiceCase
            Int32.TryParse(vm.FlatNr, out int flatNr);
            var serviceCase = new ServiceReference1.ServiceCase
            {
                Name = vm.Name,
                FlatNr = flatNr,
                ContactEmail = vm.ContactEmail,
            };

            // skapa en lista för eventuella registreringsfel
            var errorLog = new List<ErrorLogItem>();

            try
            {
                // Anslut till webbservicen, lägg till meddelandetexten som ett inlägg och registrera ärendet
                var service = new ServiceReference1.Service1Client();
                serviceCase = service.CreateCase(serviceCase);
                serviceCase.Posts = new ServiceReference1.ServiceCasePost[1] 
                {
                    service.AddPost(serviceCase.CaseNr, post)
                };

                // Konrollera att registreringen gick bra
                ValidateEqual(vm.Name, serviceCase.Name, errorLog);
                ValidateEqual(vm.FlatNr, serviceCase.FlatNr.ToString(), errorLog);
                ValidateEqual(vm.ContactEmail, serviceCase.ContactEmail, errorLog);
                ValidateEqual(vm.NewPostMessage, serviceCase.Posts?[0].Message ?? "", errorLog);
            }
            catch (CommunicationException ex)
            {
                // Ifall webbservicen inte hittades e.d.
                errorLog.Add(new ErrorLogItem("CommunicationException", ex.Message));
                // TODO: Mejla alla uppkomna fel till en admin-webbadress
                Debug.WriteLine("ERROR: " + ex.Message);
            }

            //Kolla att det inte blev några fel
            if (errorLog.Count() == 0 
                && (serviceCase.Errors == null || serviceCase.Errors.Count() == 0)
                && (serviceCase.Posts.LastOrDefault().Errors == null || serviceCase.Posts.LastOrDefault().Errors.Count()==0))
            {
                // Mappa till resultat-vymodellen
                var vmResult = new RegistrationConfirmationViewModel
                {
                    CaseNr = serviceCase.CaseNr.ToString(),
                    Name = serviceCase.Name,
                    FlatNr = serviceCase.FlatNr.ToString(),
                    ContactEmail = serviceCase?.ContactEmail ?? "".ToString(),
                    Message = serviceCase.Posts[0].Message,
                };
                //SendMailSimple.SendRegistrationConfirmation(vmResult);
                return View("RegistrationConfirmation", vmResult);
            }

            // Ifall registreringen misslyckades:
            vm.TryCount++;
            // För att vm.TryCount++ ska appliceras så måste vi rensa ModelState-cashen med ModelState.Clear()
            // läs här för förklaring:
            // https://blogs.msdn.microsoft.com/simonince/2010/05/05/asp-net-mvcs-html-helpers-render-the-wrong-value/
            ModelState.Clear();
            return View("RegistrationError", vm);
        }

        [HttpPost]
        public ActionResult EmailRegisterServiceCase(ServiceCaseViewModel vm)
        {
            var vmResult = new RegistrationConfirmationViewModel
            {
                Name = vm.Name,
                FlatNr = vm.FlatNr,
                ContactEmail = vm.ContactEmail,
                Message = vm.NewPostMessage,
            };
            SendMailSimple.SendServiceCase(vmResult);
            return View("EmailRegistrationConfirmation", vmResult);
        }

        private bool ValidateEqual(string value1, string value2, List<ErrorLogItem> errorLog)
        {
            if (value1 != value2)
            {
                var error = new ErrorLogItem("notEqual", "'" + value1 + "' IS NOT EQUAL TO '" + value2 + "'");
                errorLog.Add(error);
                Debug.WriteLine("ERROR: " + error.Description);
                return false;
            }
            return true;
        }
    }
}

ETB310_TennantWebsite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ETB310_TennantWebsite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ETB310_TennantWebsite/Views/Home/CreateServiceCase.cshtml
@model ETB310_TennantWebsite.Models.ServiceCaseViewModel
@{
    ViewBag.Title = "CreateServiceCase";
}
<h2>Anmäl ett fel</h2>

@using (Html.BeginForm("CreateServiceCase", "Home", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12 alert-danger site-alert">
            @Html.ValidationMessageFor(vm => vm.Name)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">namn </div>
        <div class="col-md-3 ">@Html.TextBoxFor(vm => vm.Name, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-12 alert-danger site-alert">@Html.ValidationMessageFor(vm => vm.FlatNr)</div>
    </div>
    <div class="row">
        <div class="col-md-2">lägenhetsnummer </div>
        <div class="col-md-3">@Html.TextBoxFor(vm => vm.FlatNr, new { @class = "form-control" })</div>
    </div>
    <div class="row">
        <div class="col-md-12 alert-danger  site-alert">@Html.ValidationMessageFor(vm => vm.NewPostMessage)</div>
    </div>
    <div>ärendebeskrivning </div>
    <div>@Html.TextAreaFor(vm => vm.NewPostMessage, 10, 80, new { @class = "form-control" })</div>
    <input type="submit" value="skicka" class="" />
}

ETB310_TennantWebsite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-lg-8">
        <img class="img-responsive" src="~/Content/images/chuttersnap-597664-unsplash.jpg" />
    </div>
    <div class="clearfix space-under"></div>
    <div>
        <a href="https://unsplash.com/photos/tvHsxfMp8Gw?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
            Photo by chuttersnap on Unsplash
        </a>        
    </div>
</div>

ETB310_TennantWebsite/Views/ServiceCase/EmailRegistrationConfirmation.cshtml
@model ETB310_TennantWebsite.Models.RegistrationConfirmationViewModel
@{
    ViewBag.Title = "Confirmation";
}
<h2>Tack för din registrering!</h2>
<p>Ditt ärende har nu skickats som e-post</p>

@{
    Html.RenderPartial("_displayServiceCase", Model);
}
<p>Vänliga hälsningar THN-AB.</p>

ETB310_TennantWebsite/Views/ServiceCase/RegisterServiceCase.cshtml
@model ETB310_TennantWebsite.Models.ServiceCaseViewModel
@{
    ViewBag.Title = "RegisterServiceCase";
}

<h2>Anmäl ett serviceärende</h2>

@using (Html.BeginForm("RegisterServiceCase", "ServiceCase", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12 alert-danger site-alert">
            @Html.ValidationMessageFor(vm => vm.Name)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">Namn: </div>
        <div class="col-md-4 ">@Html.TextBoxFor(vm => vm.Name, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-12 alert-danger site-alert">@Html.ValidationMessageFor(vm => vm.FlatNr)</div>
    </div>
    <div class="row">
        <div class="col-md-2">lägenhetsnummer: </div>
        <div class="col-md-4">@Html.TextBoxFor(vm => vm.FlatNr, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-12 alert-danger site-alert">@Html.ValidationMessageFor(vm => vm.ContactEmail)</div>
    </div>
    <div class="row">
        <div class="col-md-2">E-postadress: </div>
        <div class="col-md-4">@Html.TextBoxFor(vm => vm.ContactEmail, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-12 alert-danger  site-alert">@Html.ValidationMessageFor(vm => vm.NewPostMessage)</div>
    </div>
    <div>Ärendebeskrivning </div>
    <div>@Html.TextAreaFor(vm => vm.NewPostMessage, 10, 40, new { @class = "form-control" })</div>

    <input type="submit" value="skicka" class="btn btn-default" />
}

ETB310_TennantWebsite/Views/ServiceCase/RegistrationConfirmation.cshtml
@model ETB310_TennantWebsite.Models.RegistrationConfirmationViewModel
@{
    ViewBag.Title = "Confirmation";
}
<h2>Tack för din registrering!</h2>
<p>Vi har nu tagit emot ditt ärende. Du har fått ärendenummer {@Model.CaseNr].</p>

@{
    Html.RenderPartial("_displayServiceCase", Model);
}

<p>Vänliga hälsningar THN-AB.</p>

ETB310_TennantWebsite/Views/ServiceCase/RegistrationError.cshtml
@model ETB310_TennantWebsite.Models.ServiceCaseViewModel
@{
    ViewBag.Title = "Confirmation";
}
<h2>Tyvärr, något gick fel...</h2>
<p>
    Tyvärr, något gick fel vid registreringen och ett ärende kunde inte skapas.<br />
    Om du vill kan vi försöka skicka in ditt ärende igen.<br />
    Vi kan också mejla in ärendet åt dig, så lägger vi sen in det i systemet manuellt.
</p>

<div class="clearfix">
    <div>
        <div class="side-by-side ">
            @using (Html.BeginForm("RegisterServiceCase", "ServiceCase", FormMethod.Post))
            {
                @Html.HiddenFor(vm => vm.Name, new { @class = "form-control" })
                @Html.HiddenFor(vm => vm.ContactEmail, new { @class = "form-control" })
                @Html.HiddenFor(vm => vm.FlatNr, new { @class = "form-control" })
                @Html.HiddenFor(vm => vm.NewPostMessage, new { @class = "form-control" })
                @Html.HiddenFor(vm => vm.TryCount)
                <input type="submit" value="Försök igen" class="btn btn-default" />
            }
        </div>
        @if (Model.TryCount > 1)
        {
            <div class="btn-extra-info">
                försök @Model.TryCount
            </div>
        }
        <div class="clearfix space-under"></div>
        <div class="side-by-side ">
            @using (Html.BeginForm("EditServiceCase", "ServiceCase", FormMethod.Post))
            {
                @Html.HiddenFor(vm => vm.Name, new { @class = "form-control" })
                @Html.HiddenFor(vm => vm.ContactEmail, new { @class = "form-control" })
                @Html.HiddenFor(vm => vm.FlatNr, new { @class = "form-control" })
                @Html.HiddenFor(vm => vm.NewPostMessage, new { @class = "form-control" })
                @Html.HiddenFor(vm => vm.TryCount)
                <input type="submit" value="Redigera ärendet" class="btn btn-default" />
            }
        </div>
        <div class="clearfix space-under"></div>

        @using (Html.BeginForm("EmailRegisterServiceCase", "ServiceCase", FormMethod.Post))
        {
            @Html.HiddenFor(vm => vm.Name, new { @class = "form-control" })
            @Html.HiddenFor(vm => vm.ContactEmail, new { @class = "form-control" })
            @Html.HiddenFor(vm => vm.FlatNr, new { @class = "form-control" })
            @Html.HiddenFor(vm => vm.NewPostMessage, new { @class = "form-control" })
            <input type="submit" value="Skicka ärendet som E-post" class="btn btn-default" />
        }

    </div>
</div>


<hr />
<p>Ärende ser ut som följer:</p>
    Namn: @Model.Name<br />
    E-post: @Model.ContactEmail<br />
    Lägenhetsnummer: @Model.FlatNr<br />
    Meddelande: @Model.NewPostMessage<br />
    <hr />

ETB310_TennantWebsite/Views/ServiceCase/_displayServiceCase.cshtml
@model ETB310_TennantWebsite.Models.RegistrationConfirmationViewModel

<hr />
<p>Ditt ärende ser ut som följer:</p>
Namn: @Model.Name<br />
Epost: @Model.ContactEmail<br />
Lägenhetsnummer: @Model.FlatNr<br />
Meddelande: @Model.Message
<hr />

ETB310_TennantWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
                <a href="@Url.Action("Index", "Home", null)">
                    <img class="menu-logo" src="/Content/images/ThbAbLogo.png" alt="THB-AB logo"/></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="menu-main-item">@Html.ActionLink("Välkommen", "Index", "Home")</li>
                    <li class="menu-main-item">@Html.ActionLink("Om THB-AB", "About", "Home")</li>
                    <li class="menu-main-item">@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li class="menu-main-item">@Html.ActionLink("Anmäl ett serviceärende", "Index", "ServiceCase")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="menu-spacer clearfix"></div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Femskägg</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>